--- 
document: 
  description: |
    Questo documento contiene il Piano Nazionale Innovazione 2025 presentato il 17 dicembre 2019 a Roma, dalla Ministra Paola Pisano.   
  name: "Piano Nazionale Innovazione 2025"
  tags: 
    - piano nazionale innovazione
    - italia 2025
